### PR TITLE
Fix deps

### LINKED ISSUE #9: Fix Dependencies in Recipe
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

**Issue**: Dependencies install perfectly fine, but won't build when added to conda-forge feedstock (See #7 for addition)

I have tested just installed the dependencies according to feedstock manually through the following docker image, but both build perfectly fine whereas the tests in #7 keep failing for Python 3.6 and Python 3.7. It also failed in #8, but I closed that one.

```shell
$ docker run -it centos:7 bash 
$ yum install wget
$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ chmod +x ./Miniconda3-latest-Linux-x86_64.sh
$ ./Miniconda3-latest-Linux-x86_64.sh
$ source ~/.bashrc
$ conda create -c conda-forge -n pytkdocs-36 python=3.6 pytkdocs "astunparse>=1.6.3" "dataclasses>=0.7,<0.9" "typing_extensions>=3.7.4.3" "cached-property>=1.5.2"
$ conda create -c conda-forge -n pytkdocs-37 python=3.7 pytkdocs "astunparse>=1.6.3" "dataclasses>=0.7,<0.9" "typing_extensions>=3.7.4.3" "cached-property>=1.5.2"
```

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #9.

### CODE REVIEW

**Comment by hadim** [comment]
@bandersen23 let see whether it works here.

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
I feel like `- six >=1.6.1,<2.0` in the `astunp4arse` is causing the issues for the build `py<38`. Not sure how to fix that...

See https://github.com/conda-forge/astunparse-feedstock/blob/master/recipe/meta.yaml

**Comment by hadim** [comment]
I don't get what is happening here.

@conda-forge/help-python this recipe has some python constraints and it seems to confuse the conda solver but I am not sure I understand the errors. If a second eye could have a look, please.

**Comment by bandersen23** [comment]
@hadim Thanks for the PR. I'm not understanding the errors either. I'll have to keep searching to see what the issue is.

**Comment by bandersen23** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
This PR is failing because conda-forge doesn't have `cached-property >=1.5.2`

```
conda search conda-forge::cached-property
Loading channels: done
# Name                       Version           Build  Channel             
cached-property                1.3.0          py27_0  conda-forge         
cached-property                1.3.0          py35_0  conda-forge         
cached-property                1.3.0          py36_0  conda-forge         
cached-property                1.4.0          py27_0  conda-forge         
cached-property                1.4.0          py35_0  conda-forge         
cached-property                1.4.0          py36_0  conda-forge         
cached-property                1.4.3          py27_0  conda-forge         
cached-property                1.4.3          py35_0  conda-forge         
cached-property                1.4.3          py36_0  conda-forge         
cached-property                1.4.3            py_1  conda-forge         
cached-property                1.5.1            py_0  conda-forge         
```

**Comment by nehaljwani** [comment]
For some reason, the CI build for https://github.com/conda-forge/cached-property-feedstock/pull/10 didn't upload the artifacts.

**Comment by bandersen23** [comment]
@nehaljwani Thanks for checking this out! The anaconda channel has it... any chance we can use that one?

**Comment by nehaljwani** [comment]
Ah, looks like we have one with an underscore:
```
$ conda search conda-forge::cached_property

Loading channels: done
# Name                       Version           Build  Channel             
cached_property                1.5.2    pyhd8ed1ab_0  conda-forge     
```

**Comment by hadim** [comment]
I remember having tried `cached_property` too. Maybe at that time, it was another issue. Can you take over this PR @bandersen23 ?

**Comment by bandersen23** [comment]
Thanks for the commit @hadim. I'll wait on the checks and go from here. Thanks for all the help so far!

**Comment by nehaljwani** [comment]
I've raised this issue at https://github.com/conda-forge/cached-property-feedstock/issues/13

**Comment by hadim** [comment]
Hey it seems to be working!

Thanks @nehaljwani for the help here.

**Comment by bandersen23** [comment]
Yes we're so close, just one more failing build to troubleshoot.

**Comment by nehaljwani** [comment]
No clue why this one failed. It builds fine locally for py36 on win-64.

Let's try a retrigger. @conda-forge-admin Please restart ci!

**Comment by nehaljwani** [comment]
Failed again 😭  Calling in the big guns.

cc @conda-forge/core

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
It looks like the build worked with `mambabuild` but not with `conda`?

**Comment by chrisburr** [comment]
> It looks like the build worked with `mambabuild` but not with `conda`?

Yup though I'm not sure why and I haven't had chance to debug further.

**Comment by bandersen23** [comment]
This is the first I'm learning about `mambabuild`, but from what I'm seeing I don't understand why it would succeed there and not in `conda`. I appreciate all the help.

**Comment by hadim** [comment]
`mamba` and `conda` use a different dep solver under the hood which probably explains the difference. That being said I have also tested to install those deps in a clean local conda env with `conda` on windows and it works so I am a bit confused about this CI error.

@chrisburr is that already possible to fully enable `mamba`  on a feedstock?

**Comment by bandersen23** [comment]
Anyone have any other ideas for this? The only thing I thought of was if it's an Azure error? 

If there's no way to fix it as of now, if I merge as is will win-64 python 36 be the only version that doesn't build then?

**Comment by hadim** [comment]
It's not ideal for sure but if we want to merge this we could disable win-64 and py36 with `skip: True  # [win64 and py36]`. Maybe wait for a conda-forge dev to confirm.

**Comment by dhirschfeld** [comment]
3.6 is EOL this year. I think it's fine to skip it on Windows and only bother revisiting if anyone complains. No point putting in a lot of effort if there are no users on that platform. If there *are* users you'll probably hear about it soon enough...

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
@bandersen23 you can merge!

Thanks, everyone.

**Comment by bandersen23** [comment]
Thank you to everyone who assisted with this! I learned a lot in the process.

**Pull request merged**
