### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bandersen23**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
Thanks @bandersen23 !

**Comment by hadim** [comment]
`astunparse ` must be in `run` no? or the dep won't install with `conda install`. You can put a python selector eventually.

**Comment by bandersen23** [comment]
@hadim When the master branch is built, see if thy fixes it! If not, I'll have to troubleshoot at a later time.

**Comment by bandersen23** [comment]
Oh that's true. Do you know how to do you do a Python selector in the conda recipe? If not, I'll have to look it up!

**Comment by hadim** [comment]
Try this `- astunparse  # [py<39]`

**Comment by bandersen23** [comment]
I'll try that this evening.

**Pull request merged**
